name: biblioteca_libros
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  provider: ^6.0.0
  flutter_secure_storage: ^9.2.2
  flutter_pdfview: ^1.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pdfs/sample1.pdf
    - assets/pdfs/sample2.pdf
    - assets/pdfs/yumemiruvolumen1.pdf
    - assets/pdfs/yumemiruvolumen2.pdf
    - assets/pdfs/yumemiruvolumen3.pdf
    - assets/pdfs/yumemiruvolumen4.pdf
    - assets/pdfs/yumemiruvolumen5.pdf
    - assets/images/background.jpg
